package mindmanager.forms;

import java.awt.Toolkit;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import mindmanager.bancodedados.ConexaoImpressao;
import mindmanager.dao.pacienteDao;
import mindmanager.logica.Impressao;
import mindmanager.logica.atributos;
import net.sf.jasperreports.engine.JRException;

public class JFLaudos extends javax.swing.JDialog {

    DefaultTableModel tmPacientes = new DefaultTableModel(null, new String []{"Código","Nome"});
    List<atributos> pacientes;
    ListSelectionModel lsmPacientes;
    /**
     * Creates new form NewJDialog
     */
    public JFLaudos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
          jTLaudo.setEnabledAt(1, false);
        
          this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/mindmanager/imagens/logo_mindmanager(48x48).png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTLaudo = new javax.swing.JTabbedPane();
        jPRelatorio = new javax.swing.JPanel();
        jLLaudo = new javax.swing.JLabel();
        jSRelatorio = new javax.swing.JScrollPane();
        jTALaudo = new javax.swing.JTextArea();
        jLSelecione = new javax.swing.JLabel();
        jTPesquisar = new javax.swing.JTextField();
        jBPesquisa = new javax.swing.JButton();
        jBAdicionar = new javax.swing.JButton();
        jBImprimir = new javax.swing.JButton();
        jTCodigo = new javax.swing.JTextField();
        jPPaciente = new javax.swing.JPanel();
        jSPaciente = new javax.swing.JScrollPane();
        jTPaciente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Laudos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mindmanager/imagens/bg.jpg"))); // NOI18N

        jLLaudo.setText("Digite o laudo psicológico");

        jTALaudo.setColumns(20);
        jTALaudo.setEditable(false);
        jTALaudo.setRows(5);
        jTALaudo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTALaudoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTALaudoKeyReleased(evt);
            }
        });
        jSRelatorio.setViewportView(jTALaudo);

        jLSelecione.setText("Selecione o paciente:");

        jTPesquisar.setEditable(false);

        jBPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mindmanager/imagens/Start-Menu-Search-icon.png"))); // NOI18N
        jBPesquisa.setText("Buscar");
        jBPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisaActionPerformed(evt);
            }
        });

        jBAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mindmanager/imagens/add (25x25).png"))); // NOI18N
        jBAdicionar.setToolTipText("Adicionar");
        jBAdicionar.setEnabled(false);
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jBImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mindmanager/imagens/print-icon (1).png"))); // NOI18N
        jBImprimir.setText("Imprimir");
        jBImprimir.setEnabled(false);
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });

        jTCodigo.setEditable(false);

        javax.swing.GroupLayout jPRelatorioLayout = new javax.swing.GroupLayout(jPRelatorio);
        jPRelatorio.setLayout(jPRelatorioLayout);
        jPRelatorioLayout.setHorizontalGroup(
            jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLLaudo)
                        .addGroup(jPRelatorioLayout.createSequentialGroup()
                            .addGroup(jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRelatorioLayout.createSequentialGroup()
                                    .addComponent(jLSelecione)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBPesquisa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBAdicionar))
                                .addComponent(jSRelatorio))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRelatorioLayout.createSequentialGroup()
                        .addComponent(jBImprimir)
                        .addContainerGap())))
        );
        jPRelatorioLayout.setVerticalGroup(
            jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSelecione)
                    .addComponent(jBAdicionar)
                    .addComponent(jBPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLLaudo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBImprimir)
                .addContainerGap())
        );

        jTLaudo.addTab("Laudo", jPRelatorio);

        jTPaciente.setModel(tmPacientes);
        jTPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPacienteMouseClicked(evt);
            }
        });
        jSPaciente.setViewportView(jTPaciente);

        javax.swing.GroupLayout jPPacienteLayout = new javax.swing.GroupLayout(jPPaciente);
        jPPaciente.setLayout(jPPacienteLayout);
        jPPacienteLayout.setHorizontalGroup(
            jPPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );
        jPPacienteLayout.setVerticalGroup(
            jPPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        jTLaudo.addTab("Paciente", jPPaciente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTLaudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTLaudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-646)/2, (screenSize.height-472)/2, 646, 472);
    }// </editor-fold>//GEN-END:initComponents
String laudo;
    private void jTALaudoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTALaudoKeyPressed
        if (jTALaudo.getText().length() < 1000) {
            laudo = jTALaudo.getText();
        }


        if (jTALaudo.getText().length() > 999) {
            if (evt.getKeyCode() != 10) {
                jTALaudo.setText("");
                jTALaudo.setText(laudo);
            }

        }
    }//GEN-LAST:event_jTALaudoKeyPressed

    private void jTALaudoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTALaudoKeyReleased
        if (jTALaudo.getText().length() < 1000) {
            laudo = jTALaudo.getText();
        }


        if (jTALaudo.getText().length() > 999) {
            if (evt.getKeyCode() != 10) {
                jTALaudo.setText("");
                jTALaudo.setText(laudo);
            }

        }
    }//GEN-LAST:event_jTALaudoKeyReleased

    private void jBPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisaActionPerformed
        try {
            jTPesquisar.setText("");
            listarPacientes();
            jTLaudo.setEnabledAt(1, true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problemas no botão de pesquisa.\n" + ex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nenhhum paciente encontrado.\n" + e);
        }
    }//GEN-LAST:event_jBPesquisaActionPerformed

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        try {
            alteraPaciente();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problema no botão alterar.");
        }
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
        if (!jTALaudo.getText().equals("")) {
            abrirRelatorioClientes();
        } else {
            JOptionPane.showMessageDialog(null, "Digite algo no laudo para ser impresso.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBImprimirActionPerformed

    private void jTPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPacienteMouseClicked
        linhaSelecionadaPacientes(jTPaciente);
    }//GEN-LAST:event_jTPacienteMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        sair();
    }//GEN-LAST:event_formWindowClosing

    //Adiciona laudo na ficha do paciente
      private void alteraPaciente() throws SQLException {
        if(jTPaciente.getSelectedRow() != -1){
             UIManager.put("OptionPane.noButtonText", "Não");  
         UIManager.put("OptionPane.yesButtonText", "Sim");
            int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente adicionar laudo?", "Confirmação", 0,3);
         if (resp == 0){
              if(verificaDados()){
                atributos at = new atributos();
                pacienteDao dao =  new pacienteDao();
                
                at.setLaudo(jTALaudo.getText());
                at.setNomePaciente(jTPesquisar.getText());
               
                dao.adicionaLaudo(at);
                 JOptionPane.showMessageDialog(null,"Laudo adicionado com sucesso.","Laudo",JOptionPane.INFORMATION_MESSAGE);
                  listarPacientes();
                  laudo ="";
                  jTLaudo.setSelectedComponent(jPRelatorio);
                  jTALaudo.setEditable(false);
                  jBAdicionar.setEnabled(false);
                   
            }
        }
         }
           
         }
     
      //Mostra os pacientes cadastrados
     private void mostraPesquisaPaciente(List<atributos> pacientes) {
      while(tmPacientes.getRowCount()>0){
          tmPacientes.removeRow(0);
      }
        if(pacientes.isEmpty()){
          JOptionPane.showMessageDialog(null,"Nenhum paciente encontrado.","Pesquisa",JOptionPane.INFORMATION_MESSAGE);
      }else{
            jTLaudo.setSelectedComponent(jPPaciente);
          String []linha = new String [] {null, null};
          for (int i = 0; i < pacientes.size(); i++){
              tmPacientes.addRow(linha);
              tmPacientes.setValueAt(pacientes.get(i).getCodigoPaciente(), i, 0);
              tmPacientes.setValueAt(pacientes.get(i).getNomePaciente(), i, 1);
          }
      }
    }
    
     //Lista a pesquisa feita
    protected void listarPacientes() throws SQLException{
        pacienteDao dao = new pacienteDao ();
       pacientes = dao.getListaNomePaciente("%" + jTPesquisar.getText() + "%");
        mostraPesquisaPaciente(pacientes);
    }
     
    //Verifica se os dados obrigatórios foram preenchidos
      public boolean verificaDados(){
        if(jTALaudo.getText().equals("") || jTPesquisar.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Insira alguma informação no laudo.","Erro", JOptionPane.WARNING_MESSAGE);
        return false;
        }else{
            return true;
        }
        
    }
      
      //Joga os dados da linha selecionada na tabela para os TextFields
      private void linhaSelecionadaPacientes(JTable tabela){
          
        if(jTPaciente.getSelectedRow()!=-1){
        jTCodigo.setText(String.valueOf(pacientes.get(tabela.getSelectedRow()).getCodigoPaciente()));
        jTPesquisar.setText(pacientes.get(tabela.getSelectedRow()).getNomePaciente());
        jTALaudo.setText(pacientes.get(tabela.getSelectedRow()).getLaudo());
        jTLaudo.setSelectedComponent(jPRelatorio);
        jTLaudo.setEnabledAt(1, false);
        laudo = jTALaudo.getText();
        jBAdicionar.setEnabled(true);
        jTALaudo.setEditable(true);
        jBImprimir.setEnabled(true);
        } else{
            
           jTALaudo.setText("");
       }
      
    }
      
      //Método de impressão
      public void abrirRelatorioClientes() {
	 
	    // note que estamos chamando o novo relatório
	    InputStream inputStream = getClass().getResourceAsStream( "/Laudos.jasper" );
	 
	    // mapa de parâmetros do relatório
	    Map parametros = new HashMap();
	 
	    /*
	     * Insere o parâmetro primeiroNome no mapa, com o valor F%
	     * ou seja, todos os clientes que tenham primeiro nome começando
	     * com a letra F.
	     */
	    parametros.put( "codigoPaciente", jTCodigo.getText() );
	 
	    // outros possíveis parâmetros aqui...
	 
	    try {
	 
	        // abre o relatório
	        Impressao.openReport( "Laudos", inputStream, parametros,
	                ConexaoImpressao.getMindConnection() );
                
	  this.dispose();
	    } catch ( SQLException exc ) {
	        exc.printStackTrace();
	    } catch ( JRException exc ) {
	        exc.printStackTrace();
	    }
	 
	}
    
     public void sair(){
         UIManager.put("OptionPane.noButtonText", "Não");  
         UIManager.put("OptionPane.yesButtonText", "Sim");
         int x = JOptionPane.showConfirmDialog(null, "Deseja encerrar o laudo?", "Alerta",0, 2);
        
        if (x==0) {
        this.dispose();
        
        }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLaudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLaudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLaudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLaudos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                JFLaudos dialog = new JFLaudos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBImprimir;
    private javax.swing.JButton jBPesquisa;
    private javax.swing.JLabel jLLaudo;
    private javax.swing.JLabel jLSelecione;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPPaciente;
    private javax.swing.JPanel jPRelatorio;
    private javax.swing.JScrollPane jSPaciente;
    private javax.swing.JScrollPane jSRelatorio;
    private javax.swing.JTextArea jTALaudo;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTabbedPane jTLaudo;
    private javax.swing.JTable jTPaciente;
    private javax.swing.JTextField jTPesquisar;
    // End of variables declaration//GEN-END:variables
}
